### PR TITLE
Fix instructions to uninstall the collector on Windows

### PR DESCRIPTION
**Pull request by pjanotti**
**Requirements**

- [X] Content follows Splunk guidelines for style and formatting.
- [X] You are contributing original content.

**Describe the change**

The alternative instructions are incorrect. Tested the updated ones on my machine.

### CODE REVIEW

**Comment by pjanotti** [comment]
@theletterf @RassK 🤔 we should remove the "nice" WMI instructions so there is no need for alternative instructions.

**Review by RassK — APPROVED** [review]

**Comment by RassK** [comment]
@pjanotti I'm wondering what was the intention originally with `.uninstall()`. Can't see any return types that have this method 🤷 
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-itemproperty?view=powershell-7.4

**Review by theletterf — APPROVED** [review]
Thanks, Paulo!

**Comment by RassK** [comment]
@pjanotti another idea. If you can transfer the "complex" uninstall to install.ps1?  
`install.ps1 -uninstall` if the flag is set, then instead of running the main path, you invoke internal uninstall function? - so the docs can be more simpler containing only `install.ps1 -uninstall`

**Comment by pjanotti** [comment]
@RassK I like the idea of uninstalling from the script since (I assume) the bundle with the install script is typically kept on the machine. The only concern that I have is that the script can install instrumentation (right now just .NET but we are adding others) and them the question becomes if it should support specific uninstall for collect, instrumentations, etc or just a global uninstall everything from the bundle. At first I think uninstall everything from the bundle seems reasonable.

@jeffreyc-splunk what do you think?

**Comment by jeffreyc-splunk** [comment]
> @RassK I like the idea of uninstalling from the script since (I assume) the bundle with the install script is typically kept on the machine. The only concern that I have is that the script can install instrumentation (right now just .NET but we are adding others) and them the question becomes if it should support specific uninstall for collect, instrumentations, etc or just a global uninstall everything from the bundle. At first I think uninstall everything from the bundle seems reasonable.
> 
> @jeffreyc-splunk what do you think?

- Adding an uninstall option to the script is probably a good idea, since we already have that for our [linux script](https://github.com/signalfx/splunk-otel-collector/blob/main/internal/buildscripts/packaging/installer/install.sh#L724).
- Our current installation instructions doesn't save the installer script locally on the host:
  ```
  & {Set-ExecutionPolicy Bypass -Scope Process -Force; $script = ((New-Object System.Net.WebClient).DownloadString('https://dl.signalfx.com/splunk-otel-collector.ps1')); $params = @{access_token = "SPLUNK_ACCESS_TOKEN"; realm = "SPLUNK_REALM"}; Invoke-Command -ScriptBlock ([scriptblock]::Create(". {$script} $(&{$args} @params)"))}
  ```
  Assuming the user hasn't manually saved the script on the host, they'd have to do something like this after we add the uninstall option:
  ```
  & {Set-ExecutionPolicy Bypass -Scope Process -Force; $script = ((New-Object System.Net.WebClient).DownloadString('https://dl.signalfx.com/splunk-otel-collector.ps1')); $params = @{uninstall = 1}; Invoke-Command -ScriptBlock ([scriptblock]::Create(". {$script} $(&{$args} @params)"))}
  ```

**Comment by theletterf** [comment]
Would having an `uninstall.ps1` script go against DRY principles or similar? :-)

**Comment by pjanotti** [comment]
> Would having an uninstall.ps1 script go against DRY principles or similar? :-)

I think the idea was install to have a single script with another option to allow the uninstallation. Notice that we don't save the script so I think it is better actually to keep just the latest instructions and remove the WMI ones (since WMI registration of installed programs is known to get corrupted).

**Pull request merged**
