### PR TITLE
Add collector upgrade instructions

### PR DESCRIPTION
**Pull request by jeffreyc-splunk**
**Requirements**

- [X] Content follows Splunk guidelines for style and formatting.
- [X] You are contributing original content.

**Describe the change**

Copied from https://github.com/signalfx/splunk-otel-collector/blob/main/docs/getting-started/linux-installer.md#collector-upgrade

### CODE REVIEW

**Comment by aurbiztondo-splunk** [comment]
Thanks for the PR, @jeffreyc-splunk! I have a few questions, I'll get in touch!

**Comment by aurbiztondo-splunk** [comment]
Closing, as discussed with @jeffreyc-splunk.

**Comment by pohannigansfx** [comment]
@aurbiztondo-splunk was this closed after being merged? Looks like the MR is still active.

**Comment by jeffreyc-splunk** [comment]
> @aurbiztondo-splunk was this closed after being merged? Looks like the MR is still active.

This is no longer needed since I overlooked our existing doc with this info: https://docs.splunk.com/Observability/gdi/opentelemetry/otel-upgrade.html#upgrade-the-collector-for-linux

**Pull request closed without merging**
